use_frameworks!

platform :ios, '8.0'

target 'podZZTest_Example' do
  pod 'podZZTest', :path => '../'

  target 'podZZTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
